'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Moca.Db
Imports Moca.Db.Attr
Imports System.ComponentModel
Imports Moca.Win


''' <summary> 
''' DemoRow Entity 
''' </summary> 
''' <remarks></remarks> 
''' <history> 
''' </history> 
Public Class DemoRow
	Inherits RowModelBase
	Implements System.ComponentModel.INotifyPropertyChanged

#Region " Declare "
	Shared _def As IDemoDefinition

	Private _id As String

	Private _code As Integer

	Private _name As String

	Private _note As String
#End Region

#Region " Property "
    ''' <summary> 
    ''' Id (ID) Property. 
    ''' </summary> 
    <Column("ID")>
    <ColumnStyle(50)>
    <AllowMerging()>
    <Frozen()>
    Public Property Id() As String
        Get
            Return Me._id
        End Get
        Set(value As String)
            Me._id = value
            OnPropertyChanged("Id")
        End Set
    End Property

    ''' <summary> 
    ''' Code (Code) Property. 
    ''' </summary> 
    <Column("Code")> _
	<ColumnStyle(50)>
	<[ReadOnly](True)>
	Public Property Code() As Integer
		Get
			Return Me._code
		End Get
		Set(value As Integer)
			Me._code = value
			OnPropertyChanged("Code")
		End Set
	End Property

	''' <summary> 
	''' Name (Name) Property. 
	''' </summary> 
	<Column("Name")> _
	Public Property Name() As String
		Get
			Return Me._name
		End Get
		Set(value As String)
			Me._name = value
			OnPropertyChanged("Name")
		End Set
	End Property

	''' <summary> 
	''' Note (Note) Property. 
	''' </summary> 
	<Column("Note")> _
	Public Property Note() As String
		Get
			Return Me._note
		End Get
		Set(value As String)
			Me._note = value
			OnPropertyChanged("Note")
		End Set
	End Property
#End Region

#Region " PropertyChanged "
	Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

	Protected Overridable Sub OnPropertyChanged(ByVal name As String)
		RaiseEvent PropertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(name))
	End Sub
#End Region
End Class

#Region " Definition "
''' <summary> 
''' Demo Entity definition 
''' </summary> 
''' <remarks></remarks> 
''' <history> 
''' </history> 
<Table(Sys.C_CONNECTION_STRING, "tbDemo")> _
Public Interface IDemoDefinition

	''' <summary> 
	''' Id (ID) Property. 
	''' </summary> 
	<Column("ID")> _
	Property Id() As Moca.Db.DbInfoColumn

	''' <summary> 
	''' Code (Code) Property. 
	''' </summary> 
	<Column("Code")> _
	Property Code() As Moca.Db.DbInfoColumn

	''' <summary> 
	''' Name (Name) Property. 
	''' </summary> 
	<Column("Name")> _
	Property Name() As Moca.Db.DbInfoColumn

	''' <summary> 
	''' Note (Note) Property. 
	''' </summary> 
	<Column("Note")> _
	Property Note() As Moca.Db.DbInfoColumn
End Interface
#End Region
